// Generated by CoffeeScript 1.3.3
(function() {
  var Game;

  Game = (function() {

    function Game() {
      console.log('game created');
    }

    Game.prototype.start = function(id) {
      return console.log(id);
    };

    return Game;

  })();

}).call(this);
